import json
import random

cricket_base = {
    "batsmen": ["Virat Kohli", "Rohit Sharma", "Sachin Tendulkar", "Virender Sehwag", "Gautam Gambhir", "Shikhar Dhawan", "Shubman Gill", "KL Rahul", "Suryakumar Yadav", "Rishabh Pant", "Sanju Samson", "Shreyas Iyer", "Mayank Agarwal", "Prithvi Shaw", "Yashasvi Jaiswal", "Ajinkya Rahane", "Cheteshwar Pujara", "Sourav Ganguly", "Rahul Dravid", "VVS Laxman", "Steve Smith", "David Warner", "Marnus Labuschagne", "Aaron Finch", "Travis Head", "Usman Khawaja", "Matthew Hayden", "Ricky Ponting", "Adam Gilchrist", "Michael Clarke", "Kane Williamson", "Ross Taylor", "Martin Guptill", "Devon Conway", "Tom Latham", "Brendon McCullum", "Joe Root", "Jonny Bairstow", "Jason Roy", "Alex Hales", "Jos Buttler", "Alastair Cook", "Kevin Pietersen", "Babar Azam", "Fakhar Zaman", "Imam-ul-Haq", "Mohammad Rizwan", "Inzamam-ul-Haq", "Saeed Anwar", "Younis Khan", "Hashim Amla", "AB de Villiers", "Faf du Plessis", "Quinton de Kock", "Graeme Smith", "Herschelle Gibbs", "Chris Gayle", "Brian Lara", "Shivnarine Chanderpaul", "Nicholas Pooran", "Shai Hope", "Kraigg Brathwaite", "Tamim Iqbal", "Mushfiqur Rahim", "Dimuth Karunaratne", "Sanath Jayasuriya", "Kumar Sangakkara", "Mahela Jayawardene", "Pathum Nissanka", "Kusal Mendis", "Rahmanullah Gurbaz", "Ibrahim Zadran", "Hazratullah Zazai", "Paul Stirling", "Kevin O'Brien", "Rilee Rossouw", "Colin Munro", "Finn Allen", "Marlon Samuels", "Lendl Simmons", "Evin Lewis", "Mohammad Kaif", "Robin Uthappa", "Manish Pandey", "Ambati Rayudu", "Nitish Rana", "Rinku Singh", "Tilak Varma", "Sai Sudharsan", "Rajat Patidar", "Ruturaj Gaikwad", "Devdutt Padikkal", "Rahul Tripathi", "Abhishek Sharma", "Dawid Malan", "Ben Duckett", "Harry Brook", "Zack Crawley", "Ollie Pope", "Will Pucovski", "Cameron Bancroft", "Marcus Harris", "Nic Maddinson", "Peter Handscomb", "Shaun Marsh"],
    "bowlers": ["Jasprit Bumrah", "Mohammed Shami", "Mohammed Siraj", "Ishant Sharma", "Umesh Yadav", "Bhuvneshwar Kumar", "Deepak Chahar", "Shardul Thakur", "Arshdeep Singh", "Zaheer Khan", "Javagal Srinath", "Ashish Nehra", "Anil Kumble", "Harbhajan Singh", "Ravi Ashwin", "Ravindra Jadeja", "Yuzvendra Chahal", "Kuldeep Yadav", "Amit Mishra", "Axar Patel", "Washington Sundar", "Ravi Bishnoi", "Pragyan Ojha", "Piyush Chawla", "Pat Cummins", "Mitchell Starc", "Josh Hazlewood", "Nathan Lyon", "Adam Zampa", "Glenn McGrath", "Brett Lee", "Shane Warne", "Mitchell Johnson", "Jason Gillespie", "Shaun Tait", "Trent Boult", "Tim Southee", "Lockie Ferguson", "Kyle Jamieson", "Neil Wagner", "Daniel Vettori", "Shane Bond", "James Anderson", "Stuart Broad", "Jofra Archer", "Mark Wood", "Adil Rashid", "Graeme Swann", "Moeen Ali", "Chris Woakes", "Shaheen Afridi", "Haris Rauf", "Naseem Shah", "Wasim Akram", "Waqar Younis", "Shoaib Akhtar", "Saeed Ajmal", "Yasir Shah", "Shadab Khan", "Kagiso Rabada", "Anrich Nortje", "Lungi Ngidi", "Dale Steyn", "Morne Morkel", "Allan Donald", "Makhaya Ntini", "Imran Tahir", "Keshav Maharaj", "Rashid Khan", "Mujeeb Ur Rahman", "Fazalhaq Farooqi", "Naveen-ul-Haq", "Muttiah Muralitharan", "Lasith Malinga", "Chaminda Vaas", "Rangana Herath", "Wanindu Hasaranga", "Dushmantha Chameera", "Maheesh Theekshana", "Courtney Walsh", "Curtly Ambrose", "Malcolm Marshall", "Joel Garner", "Michael Holding", "Kemar Roach", "Jason Holder", "Sunil Narine", "Alzarri Joseph", "Shakib Al Hasan", "Mustafizur Rahman", "Sandeep Sharma", "Mohit Sharma", "Navdeep Saini", "Prasidh Krishna", "Kuldeep Sen", "Umran Malik", "Chetan Sakariya", "Khaleel Ahmed", "Mukesh Kumar", "Shivam Mavi", "T Natarajan", "Rahul Chahar", "Varun Chakravarthy", "Krunal Pandya", "Harshal Patel", "Avesh Khan"],
    "all_rounders": ["Hardik Pandya", "Ravindra Jadeja", "Yuvraj Singh", "Kapil Dev", "Stuart Binny", "Irfan Pathan", "Yusuf Pathan", "Krunal Pandya", "Washington Sundar", "Axar Patel", "Shivam Dube", "Nitin Saini", "Abhishek Sharma", "Ben Stokes", "Moeen Ali", "Sam Curran", "Chris Woakes", "Liam Livingstone", "Andrew Flintoff", "Ian Botham", "Cameron Green", "Mitchell Marsh", "Glenn Maxwell", "Marcus Stoinis", "Shane Watson", "Andrew Symonds", "Jimmy Neesham", "Daryl Mitchell", "Colin de Grandhomme", "Mitchell Santner", "Chris Cairns", "Rachin Ravindra", "Michael Bracewell", "Jacques Kallis", "Lance Klusener", "Shaun Pollock", "Marco Jansen", "Aiden Markram", "Imran Khan", "Shahid Afridi", "Abdul Razzaq", "Shadab Khan", "Faheem Ashraf", "Mohammad Nabi", "Azmatullah Omarzai", "Gulbadin Naib", "Shakib Al Hasan", "Mahmudullah", "Mehidy Hasan Miraz", "Jason Holder", "Andre Russell", "Dwayne Bravo", "Kieron Pollard", "Carlos Brathwaite", "Rovman Powell", "Romario Shepherd", "Odean Smith", "Sunil Narine", "Sanath Jayasuriya", "Angelo Mathews", "Thisara Perera", "Dasun Shanaka", "Chamika Karunaratne", "Wanindu Hasaranga", "Sikandar Raza", "Sean Williams", "Corey Anderson", "Ryan ten Doeschate", "Roelof van der Merwe", "Bas de Leede", "David Wiese", "Paul Collingwood", "Ravi Bopara", "Samit Patel", "Stuart Broad", "Chris Morris", "Albie Morkel", "Wayne Parnell", "Vernon Philander", "JP Duminy"],
    "terms": ["Cover Drive", "Pull Shot", "Helicopter Shot", "Straight Drive", "Sweep Shot", "Reverse Sweep", "Switch Hit", "Hook Shot", "Upper Cut", "Square Cut", "Late Cut", "Dilscoop", "Ramp Shot", "Scoop Shot", "Paddle Sweep", "Flick", "Glance", "On Drive", "Off Drive", "Lofted Drive", "Slog Sweep", "French Cut", "Inside Edge", "Outside Edge", "Defensive Block", "Natmeg Shot", "Marillier Scoop", "Reverse Hit", "Tennis Shot", "Slog Over Mid Wicket", "Bouncer", "Yorker", "Googly", "Inswinger", "Outswinger", "Slower Ball", "Doosra", "Full Toss", "Spin", "Pace", "Knuckleball", "Leg Cutter", "Off Cutter", "Beamer", "Half Volley", "Good Length", "Short Pitched", "Reverse Swing", "Carrom Ball", "Flipper", "Top Spinner", "Arm Ball", "Pace Off", "Cross Seam", "Wobble Seam", "Leg Break", "Off Break", "Slider", "Teesra", "Quicker Ball", "Bowled", "LBW", "Caught", "Run Out", "Stumped", "Hit Wicket", "Caught Behind", "Mankad", "Caught and Bowled", "Obstructing the Field", "Timed Out", "Handled the Ball", "Retired Hurt", "Retired Out", "Double Hit", "Slip", "Point", "Cover", "Mid Off", "Mid On", "Fine Leg", "Third Man", "Square Leg", "Gully", "Boundary", "Cow Corner", "Silly Point", "Long On", "Long Off", "Deep Mid Wicket", "Sweeper Cover", "Short Leg", "Leg Slip", "Fly Slip", "Deep Point", "Deep Cover", "Backward Point", "Extra Cover", "Short Fine Leg", "Short Mid Wicket", "Silly Mid On", "Silly Mid Off", "Forward Short Leg", "Leg Gully", "Wide Mid On"],
    "teams_stadiums": ["Chennai Super Kings", "Mumbai Indians", "Royal Challengers Bangalore", "Kolkata Knight Riders", "Sunrisers Hyderabad", "Delhi Capitals", "Rajasthan Royals", "Punjab Kings", "Lucknow Super Giants", "Gujarat Titans", "Sydney Sixers", "Melbourne Stars", "Perth Scorchers", "Brisbane Heat", "Lahore Qalandars", "Karachi Kings", "Peshawar Zalmi", "Quetta Gladiators", "Multan Sultans", "Trinbago Knight Riders", "Barbados Royals", "Guyana Amazon Warriors", "Melbourne Renegades", "Adelaide Strikers", "Hobart Hurricanes", "Sydney Thunder", "Oval Invincibles", "Manchester Originals", "Trent Rockets", "Southern Brave", "Wankhede Stadium", "Eden Gardens", "Chinnaswamy Stadium", "MCG", "Lord's", "SCG", "Chepauk", "Narendra Modi Stadium", "Gabba", "Adelaide Oval", "WACA", "Optus Stadium", "Arun Jaitley Stadium", "Rajiv Gandhi International", "PCA Stadium Mohali", "Green Park", "Headingley", "Trent Bridge", "Edgbaston", "Old Trafford", "SuperSport Park", "Wanderers", "Newlands", "Dubai International", "Sharjah", "Shere Bangla", "R Premadasa", "Galle Stadium", "National Stadium Karachi", "Basin Reserve", "IPL", "ODI World Cup", "T20 World Cup", "The Ashes", "World Test Championship", "Asia Cup", "Champions Trophy", "BBL", "PSL", "The Hundred", "CPL", "BPL", "SA20", "Ranji Trophy", "Vijay Hazare Trophy", "Syed Mushtaq Ali", "Border-Gavaskar Trophy", "County Championship", "Sheffield Shield", "Super Smash", "Vitality Blast", "Global T20", "IL T20", "Major League Cricket"]
}

football_base = {
    "forwards": ["Lionel Messi", "Cristiano Ronaldo", "Neymar Jr", "Kylian Mbappe", "Erling Haaland", "Robert Lewandowski", "Mohamed Salah", "Vinicius Jr", "Harry Kane", "Karim Benzema", "Sadio Mane", "Son Heung-min", "Antoine Griezmann", "Pele", "Diego Maradona", "Ronaldinho", "Ronaldo Nazario", "Thierry Henry", "Sergio Aguero", "Didier Drogba", "Alan Shearer", "Wayne Rooney", "Eric Cantona", "Gareth Bale", "Luis Suarez", "Zlatan Ibrahimovic", "Eden Hazard", "Gabriel Jesus", "Roberto Firmino", "Diogo Jota", "Darwin Nunez", "Marcus Rashford", "Anthony Martial", "Jadon Sancho", "Bukayo Saka", "Gabriel Martinelli", "Raheem Sterling", "Jack Grealish", "Phil Foden", "Julian Alvarez", "Lautaro Martinez", "Romelu Lukaku", "Paulo Dybala", "Dusan Vlahovic", "Victor Osimhen", "Khvicha Kvaratskhelia", "Rafael Leao", "Olivier Giroud", "Joao Felix", "Rodrygo", "Marco Asensio", "Ousmane Dembele", "Raphinha", "Ansu Fati", "Ferran Torres", "Leroy Sane", "Serge Gnabry", "Kingsley Coman", "Thomas Muller", "Christopher Nkunku", "Timo Werner", "Kai Havertz", "Pierre-Emerick Aubameyang", "Alexandre Lacazette", "Memphis Depay", "Cody Gakpo", "Antony", "Richarlison", "Lucas Moura", "Christian Pulisic", "Hakim Ziyech", "Riyad Mahrez", "Jamie Vardy", "Ivan Toney", "Callum Wilson", "Alexander Isak", "Ollie Watkins", "Danny Welbeck", "Dominic Calvert-Lewin"],
    "midfielders": ["Kevin De Bruyne", "Luka Modric", "Toni Kroos", "Jude Bellingham", "Andres Iniesta", "Xavi", "Steven Gerrard", "Frank Lampard", "Paul Scholes", "Ryan Giggs", "Roy Keane", "Patrick Vieira", "David Beckham", "Zinedine Zidane", "N'Golo Kante", "Bruno Fernandes", "Bernardo Silva", "Rodri", "Ilkay Gundogan", "Pedri", "Gavi", "Frenkie de Jong", "Sergio Busquets", "Casemiro", "Federico Valverde", "Eduardo Camavinga", "Aurelien Tchouameni", "Martin Odegaard", "Declan Rice", "Thomas Partey", "Mason Mount", "Enzo Fernandez", "Mateo Kovacic", "Christian Eriksen", "Thiago Alcantara", "Fabinho", "Jordan Henderson", "Alexis Mac Allister", "Moises Caicedo", "Nicolo Barella", "Hakan Calhanoglu", "Sandro Tonali", "Jamal Musiala", "Joshua Kimmich", "Leon Goretzka", "Marco Reus", "Jadon Sancho", "Julian Brandt", "Marcel Sabitzer", "Dani Olmo", "Dominik Szoboszlai", "Piotr Zielinski", "Sergej Milinkovic-Savic", "Luis Alberto", "Lorenzo Pellegrini", "Manuel Locatelli", "Adrien Rabiot", "Paul Pogba", "Nemanja Matic", "Yaya Toure", "David Silva", "Cesc Fabregas", "Bastian Schweinsteiger", "Michael Ballack", "Andrea Pirlo", "Clarence Seedorf", "Gennaro Gattuso", "Kaka", "Rui Costa", "Deco", "Mesut Ozil", "Wesley Sneijder", "Xabi Alonso", "Juan Mata", "Santi Cazorla", "James Rodriguez", "Isco"],
    "defenders_gks": ["Virgil van Dijk", "Sergio Ramos", "Thiago Silva", "Paolo Maldini", "Vincent Kompany", "John Terry", "Rio Ferdinand", "Nemanja Vidic", "Carles Puyol", "Gerard Pique", "Ruben Dias", "Marquinhos", "Eder Militao", "David Alaba", "Antonio Rudiger", "Ronald Araujo", "Jules Kounde", "Lisandro Martinez", "Raphael Varane", "William Saliba", "Gabriel Magalhaes", "Ibrahima Konate", "Josko Gvardiol", "John Stones", "Kyle Walker", "Trent Alexander-Arnold", "Andy Robertson", "Reece James", "Ben Chilwell", "Luke Shaw", "Kieran Trippier", "Joao Cancelo", "Alphonso Davies", "Achraf Hakimi", "Theo Hernandez", "Dani Carvajal", "Ferland Mendy", "Ben White", "Aaron Wan-Bissaka", "Diogo Dalot", "Matthijs de Ligt", "Dayot Upamecano", "Kim Min-jae", "Alessandro Bastoni", "Milan Skriniar", "Fikayo Tomori", "Roberto Carlos", "Cafu", "Dani Alves", "Marcelo", "Ashley Cole", "Gary Neville", "Javier Zanetti", "Philipp Lahm", "Alisson Becker", "Ederson", "Marc-Andre ter Stegen", "Thibaut Courtois", "Jan Oblak", "Emiliano Martinez", "Gianluigi Donnarumma", "Manuel Neuer", "Hugo Lloris", "Mike Maignan", "Aaron Ramsdale", "David de Gea", "Kepa Arrizabalaga", "Edouard Mendy", "Nick Pope", "Jordan Pickford", "Gianluigi Buffon", "Iker Casillas", "Petr Cech", "Edwin van der Sar", "Oliver Kahn", "Peter Schmeichel", "Lev Yashin"],
    "teams_stadiums": ["Real Madrid", "Barcelona", "Manchester United", "Liverpool", "Bayern Munich", "Juventus", "Arsenal", "Chelsea", "Manchester City", "AC Milan", "PSG", "Inter Milan", "Napoli", "Borussia Dortmund", "Atletico Madrid", "Tottenham Hotspur", "Ajax", "Benfica", "Roma", "Porto", "Sporting CP", "Marseille", "Lyon", "Boca Juniors", "River Plate", "Flamengo", "Wembley", "Old Trafford", "Anfield", "Emirates Stadium", "Stamford Bridge", "Etihad Stadium", "Santiago Bernabeu", "Camp Nou", "San Siro", "Allianz Arena", "Signal Iduna Park", "Parc des Princes", "Maracana", "La Bombonera", "Monumental", "Azteca", "Centenario", "Estadio da Luz", "Jose Alvalade", "Dragao", "De Kuip", "Johan Cruyff Arena", "FIFA World Cup", "UEFA Champions League", "Premier League", "La Liga", "Serie A", "Copa America", "Euros", "Ballon d'Or", "Europa League", "Europa Conference League", "FA Cup", "Carabao Cup", "Copa del Rey", "Coppa Italia", "DFB-Pokal", "Coupe de France", "Club World Cup", "Copa Libertadores", "Copa Sudamericana", "African Cup of Nations", "Asian Cup", "Gold Cup", "England", "Brazil", "Argentina", "France", "Germany", "Italy", "Spain", "Netherlands", "Portugal", "Uruguay", "Belgium", "Croatia", "Colombia", "Chile", "Mexico", "USA", "Japan", "South Korea"]
}

movies_base = {
    "actors": ["Leonardo DiCaprio", "Brad Pitt", "Tom Cruise", "Denzel Washington", "Johnny Depp", "Will Smith", "Keanu Reeves", "Christian Bale", "Robert Downey Jr", "Matt Damon", "Tom Hanks", "Morgan Freeman", "Harrison Ford", "Dwayne Johnson", "Chris Hemsworth", "Chris Evans", "Chris Pratt", "Ryan Reynolds", "Ryan Gosling", "Hugh Jackman", "Mark Wahlberg", "Vin Diesel", "Jason Statham", "Daniel Craig", "Joaquin Phoenix", "Matthew McConaughey", "Jake Gyllenhaal", "Bradley Cooper", "George Clooney", "Samuel L. Jackson", "Nicolas Cage", "Tom Hardy", "Cillian Murphy", "Henry Cavill", "Ben Affleck", "Michael Fassbender", "James McAvoy", "Idris Elba", "Tom Holland", "Zendaya", "Timothee Chalamet", "Austin Butler", "Oscar Isaac", "Pedro Pascal", "Adam Driver", "Andrew Garfield", "Daniel Radcliffe", "Rupert Grint", "Orlando Bloom", "Elijah Wood", "Ian McKellen", "Patrick Stewart", "Anthony Hopkins", "Al Pacino", "Robert De Niro", "Marlon Brando", "Jack Nicholson", "Clint Eastwood", "Sylvester Stallone", "Arnold Schwarzenegger", "Bruce Willis", "Mel Gibson", "Kevin Costner", "John Travolta", "Jim Carrey", "Adam Sandler", "Eddie Murphy", "Robin Williams", "Ben Stiller", "Owen Wilson", "Steve Carell", "Will Ferrell", "Jack Black", "Shah Rukh Khan", "Salman Khan", "Aamir Khan", "Amitabh Bachchan", "Rajinikanth", "Hrithik Roshan", "Prabhas", "Allu Arjun", "Kamal Haasan", "Akshay Kumar", "Ajay Devgn", "Ranbir Kapoor", "Ranveer Singh", "Varun Dhawan", "Ayushmann Khurrana", "Sidharth Malhotra", "Tiger Shroff", "Kartik Aaryan", "Vicky Kaushal", "Rajkummar Rao", "Shahid Kapoor", "Sushant Singh Rajput", "Nawazuddin Siddiqui"],
    "actresses": ["Scarlett Johansson", "Jennifer Lawrence", "Angelina Jolie", "Emma Stone", "Natalie Portman", "Margot Robbie", "Gal Gadot", "Charlize Theron", "Anne Hathaway", "Meryl Streep", "Cate Blanchett", "Julia Roberts", "Nicole Kidman", "Sandra Bullock", "Reese Witherspoon", "Kate Winslet", "Halle Berry", "Emma Watson", "Zoe Saldana", "Jessica Chastain", "Amy Adams", "Emily Blunt", "Viola Davis", "Florence Pugh", "Anya Taylor-Joy", "Ana de Armas", "Millie Bobby Brown", "Sadie Sink", "Jenna Ortega", "Rachel McAdams", "Amanda Seyfried", "Emma Thompson", "Helen Mirren", "Judi Dench", "Maggie Smith", "Keira Knightley", "Rosamund Pike", "Carey Mulligan", "Michelle Williams", "Brie Larson", "Elizabeth Olsen", "Karen Gillan", "Pom Klementieff", "Tessa Thompson", "Lupita Nyong'o", "Danai Gurira", "Letitia Wright", "Deepika Padukone", "Priyanka Chopra", "Katrina Kaif", "Kareena Kapoor", "Alia Bhatt", "Anushka Sharma", "Kriti Sanon", "Shraddha Kapoor", "Kiara Advani", "Disha Patani", "Sara Ali Khan", "Janhvi Kapoor", "Ananya Panday", "Taapsee Pannu", "Kangana Ranaut", "Vidya Balan", "Aishwarya Rai", "Kajol", "Madhuri Dixit", "Rani Mukerji", "Preity Zinta", "Karisma Kapoor", "Sushmita Sen", "Raveena Tandon", "Tabu", "Nayanthara", "Samantha Ruth Prabhu", "Rashmika Mandanna", "Pooja Hegde", "Trisha Krishnan", "Anushka Shetty", "Keerthy Suresh"],
    "movies_directors": ["The Godfather", "The Dark Knight", "Inception", "Pulp Fiction", "Forrest Gump", "The Matrix", "Fight Club", "Goodfellas", "Interstellar", "Titanic", "Avatar", "Jurassic Park", "Star Wars", "Lord of the Rings", "Harry Potter", "The Avengers", "Spider-Man", "The Lion King", "Terminator", "Gladiator", "The Shawshank Redemption", "Schindler's List", "Braveheart", "Saving Private Ryan", "The Silence of the Lambs", "Iron Man", "Captain America", "Thor", "Hulk", "Black Widow", "Hawkeye", "Wonder Woman", "The Flash", "Aquaman", "Wolverine", "Deadpool", "Black Panther", "Doctor Strange", "Ant-Man", "Captain Marvel", "Scarlet Witch", "Star-Lord", "Groot", "Rocket Raccoon", "Dune", "Oppenheimer", "Barbie", "John Wick", "Fast and Furious", "Mission Impossible", "James Bond", "Indiana Jones", "Die Hard", "Rocky", "Rambo", "Transformers", "Pirates of the Caribbean", "X-Men", "Christopher Nolan", "Steven Spielberg", "Quentin Tarantino", "Martin Scorsese", "James Cameron", "Peter Jackson", "David Fincher", "Ridley Scott", "Stanley Kubrick", "Alfred Hitchcock", "Francis Ford Coppola", "Clint Eastwood", "George Lucas", "Tim Burton", "Denis Villeneuve", "Wes Anderson", "Michael Bay", "Zack Snyder", "Guy Ritchie", "Edgar Wright", "Bong Joon Ho", "Guillermo del Toro", "Taika Waititi", "James Gunn", "J.J. Abrams", "SS Rajamouli", "Sanjay Leela Bhansali", "Karan Johar", "Zoya Akhtar", "Farhan Akhtar", "Rajkumar Hirani", "Anurag Kashyap"]
}

food_base = {
    "dishes": ["Pizza", "Burger", "Pasta", "Tacos", "Sushi", "Steak", "Fried Chicken", "Sandwich", "Hot Dog", "Salad", "Soup", "Noodles", "Rice", "Bread", "Toast", "Wrap", "Burrito", "Quesadilla", "Fajita", "Enchilada", "Nachos", "Lasagna", "Spaghetti", "Macaroni", "Ravioli", "Ramen", "Udon", "Pho", "Dumplings", "Spring Rolls", "Dim Sum", "Biryani", "Butter Chicken", "Paneer Tikka", "Dosa", "Samosa", "Naan", "Dal Makhani", "Chole Bhature", "Idli", "Vada", "Pav Bhaji", "Rogan Josh", "Palak Paneer", "Malai Kofta", "Aloo Gobi", "Chicken Tikka Masala", "Tandoori Chicken", "Seekh Kebab", "Korma", "Vindaloo", "Kadhai Paneer", "Mutter Paneer", "Bhindi Masala", "Baingan Bharta", "Dum Aloo", "Fried Rice", "Chow Mein", "Pad Thai", "Tom Yum", "Sushi Roll", "Sashimi", "Tempura", "Fish and Chips", "Roast Beef", "Shepherd's Pie", "Bangers and Mash", "Croissant", "Baguette", "Falafel", "Shawarma", "Hummus", "Kebab", "Gyros", "Moussaka", "Paella", "Tapas", "Churros", "Poutine"],
    "desserts_drinks": ["Chocolate", "Vanilla", "Strawberry", "Ice Cream", "Cake", "Brownie", "Cookie", "Donut", "Pancake", "Waffle", "Crepe", "Muffin", "Pastry", "Pie", "Tart", "Candy", "Gummy", "Lollipop", "Marshmallow", "Caramel", "Fudge", "Toffee", "Nougat", "Truffle", "Pudding", "Gelato", "Sorbet", "Frozen Yogurt", "Cheesecake", "Cupcake", "Macaron", "Coffee", "Tea", "Soda", "Juice", "Water", "Milkshake", "Smoothie", "Lemonade", "Iced Tea", "Hot Chocolate", "Matcha", "Boba", "Bubble Tea", "Wine", "Beer", "Cocktail", "Mocktail", "Margarita", "Mojito", "Martini", "Daiquiri", "Pina Colada", "Sangria", "Whiskey", "Vodka", "Rum", "Gin", "Tequila", "Brandy", "Cognac", "Champagne", "Espresso", "Cappuccino", "Latte", "Mocha", "Americano", "Macchiato", "Frappe", "Milk", "Almond Milk", "Oat Milk", "Soy Milk", "Red Bull", "Monster Energy", "Gatorade", "Kombucha"],
    "ingredients": ["Apple", "Banana", "Orange", "Grapes", "Watermelon", "Mango", "Pineapple", "Peach", "Pear", "Plum", "Cherry", "Blueberry", "Raspberry", "Blackberry", "Cranberry", "Kiwi", "Lemon", "Lime", "Grapefruit", "Melon", "Cantaloupe", "Honeydew", "Papaya", "Pomegranate", "Coconut", "Fig", "Apricot", "Nectarine", "Guava", "Avocado", "Tomato", "Potato", "Onion", "Garlic", "Carrot", "Broccoli", "Cabbage", "Spinach", "Lettuce", "Cucumber", "Pepper", "Mushroom", "Zucchini", "Eggplant", "Cauliflower", "Celery", "Asparagus", "Peas", "Beans", "Corn", "Pumpkin", "Squash", "Radish", "Turnip", "Beetroot", "Sweet Potato", "Yam", "Ginger", "Chili", "Jalapeno", "Chicken", "Beef", "Pork", "Lamb", "Turkey", "Duck", "Fish", "Salmon", "Tuna", "Cod", "Trout", "Halibut", "Shrimp", "Prawns", "Crab", "Lobster", "Oysters", "Mussels", "Clams", "Scallops", "Squid", "Octopus", "Calamari", "Bacon", "Ham", "Sausage", "Salami", "Pepperoni", "Prosciutto", "Chorizo", "Salt", "Pepper", "Sugar", "Honey", "Syrup", "Ketchup", "Mustard", "Mayonnaise", "BBQ Sauce", "Hot Sauce", "Soy Sauce", "Vinegar", "Olive Oil", "Butter", "Cheese", "Milk"]
}


# Generate 150+ arrays for each theme
def generate_categories(base_dict, target_count=160):
    categories = []
    keys = list(base_dict.keys())
    
    # First, take disjoint chunks
    for key, words in base_dict.items():
        random.shuffle(words)
        chunk_size = 20
        for i in range(0, len(words), chunk_size):
            chunk = words[i:i+chunk_size]
            if len(chunk) >= 10:
                categories.append(chunk)

    # Then build random overlapping samples to hit target count
    while len(categories) < target_count:
        # pick a random category to sample from
        key = random.choice(keys)
        pool = base_dict[key]
        sample_size = random.randint(15, 25)
        sample_size = min(sample_size, len(pool))
        sample = random.sample(pool, sample_size)
        
        # Make sure it's somewhat unique (not exactly same as existing)
        if sample not in categories:
            categories.append(sample)
    
    return categories

themes_data = {
    "themes": {
        "Cricket": generate_categories(cricket_base, 160),
        "Football": generate_categories(football_base, 160),
        "Movies": generate_categories(movies_base, 160),
        "Food": generate_categories(food_base, 160)
    }
}

with open("data/themes.json", "w") as f:
    json.dump(themes_data, f, indent=2)

print("Generated massive themes.json successfully!")
